version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      #- COSA_RSERVER_URI=
      #- COSA_RSERVER_TOP=
      - COSA_MYSQL_HOST=10.8.33.102
      - COSA_MYSQL_PORT=3306
      - COSA_MYSQL_USER=premo
      - COSA_MYSQL_PASSWORD=admin12345
      - COSA_MYSQL_DATABASE=premo
    restart: on-failure
    ports:
     - "9092:9092"
    volumes:
     - /srv/cosa_api_server/attachments:/usr/src/cosa_api_server/attachments
    container_name: cosa_api_server
